// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMRwWqQ-l8t0wcd5p8oIOs28OgBZJyDuw',
    appId: '1:552275303431:web:c7e4ebd3e05ad78ddd9ea2',
    messagingSenderId: '552275303431',
    projectId: 'messageapp-17b10',
    authDomain: 'messageapp-17b10.firebaseapp.com',
    storageBucket: 'messageapp-17b10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYCk3QreVJN0Vn56z-l9zMBxt-dZOAcDM',
    appId: '1:552275303431:android:cba85a18e51b84bddd9ea2',
    messagingSenderId: '552275303431',
    projectId: 'messageapp-17b10',
    storageBucket: 'messageapp-17b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5CiS9MM36s8cdEg-z8JIOhNpKn1cHTc',
    appId: '1:552275303431:ios:fcfc7200267a104bdd9ea2',
    messagingSenderId: '552275303431',
    projectId: 'messageapp-17b10',
    storageBucket: 'messageapp-17b10.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ5CiS9MM36s8cdEg-z8JIOhNpKn1cHTc',
    appId: '1:552275303431:ios:fcfc7200267a104bdd9ea2',
    messagingSenderId: '552275303431',
    projectId: 'messageapp-17b10',
    storageBucket: 'messageapp-17b10.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMRwWqQ-l8t0wcd5p8oIOs28OgBZJyDuw',
    appId: '1:552275303431:web:fe5027bd41edac45dd9ea2',
    messagingSenderId: '552275303431',
    projectId: 'messageapp-17b10',
    authDomain: 'messageapp-17b10.firebaseapp.com',
    storageBucket: 'messageapp-17b10.firebasestorage.app',
  );

}