const url = 'http://192.168.88.10:3000/';
final registration = "${url}api/users/register";
final login = "${url}api/users/login";
final forgotPass = "${url}api/users/forgotPass";
final verifyCode = "${url}api/users/verifyCode";
final updatePassword = "${url}api/users/updatePassword";
final updateUser = "${url}api/users/updateUser";
final verifyPassword = "${url}api/users/verifyPassword";
final addProduct = "${url}api/products/addProduct";
final addLand = "${url}api/lands/addLand";
final getProducts1 = "${url}api/products/getProducts1"; //محصول
final getProducts2 = "${url}api/products/getProducts2"; //غذائي
final getProducts3 = "${url}api/products/getProducts3"; //غير غذائي
final addToCart = "${url}api/carts/addItemToCart";
final getUserCart = "${url}api/carts/getUserCart";
final deleteItemFromCart = "${url}api/carts/deleteItemFromCart";
final registerOrder = "${url}api/orders/registerOrder";
final updateQuantities = "${url}api/products/updateProductQuantities";
final deleteUserCart = "${url}api/carts/deleteUserCart";
final getUserOrders = "${url}api/orders/getUserOrders";
final updateProductRate = "${url}api/products/updateProductRate";
final getLands = "${url}api/lands/getLands";
final getUser = "${url}api/users/getUser";
final updatePostNumber = "${url}api/users/updatePostsCount";
final registerWorkRequest = "${url}api/workRequests/registerWorkRequest";
final registerProductionLine =
    "${url}api/productionLines/registerproductionLine";
final getProductutionLines = "${url}api/productionLines/getProductionLines";
final getOwnerProducts = "${url}api/products/getOwnerProducts";
final getOwnerLands = "${url}api/lands/getOwnerLands";
final getOwnerLines = "${url}api/productionLines/getOwnerLines";
final updateLand = "${url}api/lands/updateLand";
final deleteLand = "${url}api/lands/deleteLand";
final updateProduct = "${url}api/products/updateProduct";
final deleteProduct = "${url}api/products/deleteProduct";
final updateProductionLine = "${url}api/productionLines/updateProductionLine";
final deleteLine = "${url}api/productionLines/deleteLine";
final getOwnerRequests = "${url}api/workRequests/getOwnerRequests";
final takeDecision = "${url}api/workRequests/requestDecision";
final updateWorkers = "${url}api/lands/updateWorkersNum";
final getWorkerRequests = "${url}api/workRequests/getWorkerRequests";
final getLand = "${url}api/lands/getLand";
final newBooking = "${url}api/bookings/addNewBooking";
final getPrevBooked = "${url}api/bookings/getBookedTimes";
final getCustomerBookings = "${url}api/bookings/getCustomerBooking";
final getOwnerBookings = "${url}api/bookings/getOwnerBooking";
final deleteWorkRequest = "${url}api/workRequests/deleteRequest";
final deleteBooking = "${url}api/bookings/deleteBooking";
final rateLine = "${url}api/productionLines/updateLineRate";
final updateBookingStatus = "${url}api/bookings/bookingDecision";
final getWorkers = "${url}api/workRequests/getLandWorkers";
final addLocation = "${url}api/maps/addLocation";
final getLocations = "${url}api/maps/getLocations";
final rateWorker = "${url}api/users/rateWorker";
final puplishPost = "${url}api/posts/puplishPost";
final getAllPosts = "${url}api/posts/getAllPosts";
final addComment = "${url}api/posts/addComment";
final addReaction = "${url}api/posts/addReaction";
final commentLikes = "${url}api/posts/updateCommentLikes";
final deletePost = "${url}api/posts/deletePost";
final editPost = "${url}api/posts/editPost";
final deleteComment = "${url}api/posts/deleteComment";
final editComment = "${url}api/posts/editComment";
//////////////Statisitcs
final getLandStatistic = "${url}api/lands/getLandStatistics";
final getLineStatistic = "${url}api/productionLines/getLineStatistics";
final getProducStatistic = "${url}api/products/getProductsStatistics";
final getUserStatistic = "${url}api/users/getUserStatistics";
final getAllStatistic = "${url}api/statistics/getAllStatistics";
final getAllLands = "${url}api/statistics/getAllLands";
final getAllLines = "${url}api/statistics/getAllLines";
final getAllProducts = "${url}api/statistics/getAllProducts";
//////////////Advertisements
final addMainAd = "${url}api/mainAds/addMainAd";
final deleteMainAd = "${url}api/mainAds/deleteMainAd";
final editMainAd = "${url}api/mainAds/editMainAd";
final getMainAds = "${url}api/mainAds/getMainAds";
final addProductAd = "${url}api/productAds/addProductAd";
final deleteProductAd = "${url}api/productAds/deleteProductAd";
final editProductAd = "${url}api/productAds/editProductAd";
final getProductAds = "${url}api/productAds/getProductAds";
final addCustomerAd = "${url}api/customerAds/addCustomerAd";
final deleteCustomerAd = "${url}api/customerAds/deleteCustomerAd";
final editCustomerAd = "${url}api/customerAds/editCustomerAd";
final getCustomerAds = "${url}api/customerAds/getCustomerAds";
//////////////delivery
final sendDeliveryWorkRequest = "${url}api/deliveryWorks/sendWorkRequest";
final getDeliveryWorkRequests = "${url}api/deliveryWorks/getPendingRequests";
final changeRequestStatue = "${url}api/deliveryWorks/deliveryRequestDecision";
final generateCredentials = "${url}api/deliveryWorks/generateCredentials";
final sendInfoByEmail = "${url}api/deliveryWorks/sendEmail";
//////////////////deliveryMan
final registerDeliveruMan = "${url}api/deliveryMens/registerDeliveryMan";
final getAllDeliveryMens = "${url}api/deliveryMens/getAllDekiveryMens";
final getDeliveryById = "${url}api/deliveryMens/getDeliveryById";
final editDeliveryMan = "${url}api/deliveryMens/editDeliveryMan";
final deleteDeliveryMan = "${url}api/deliveryMens/deleteDeliveryMan";
//////////////////delivery paths
final getFastDeliveryOrders = "${url}api/orders/getFastDeliveries";
