const url = 'http://192.168.1.10:3000/';
final registration = "${url}api/users/register";
final login = "${url}api/users/login";
final forgotPass = "${url}api/users/forgotPass";
final verifyCode = "${url}api/users/verifyCode";
final updatePassword = "${url}api/users/updatePassword";
final updateUser = "${url}api/users/updateUser";
final verifyPassword = "${url}api/users/verifyPassword";
final addProduct = "${url}api/products/addProduct";
final addLand = "${url}api/lands/addLand";
final getProducts1 = "${url}api/products/getProducts1"; //محصول
final getProducts2 = "${url}api/products/getProducts2"; //غذائي
final getProducts3 = "${url}api/products/getProducts3"; //غير غذائي
final addToCart = "${url}api/carts/addItemToCart";
final getUserCart = "${url}api/carts/getUserCart";
final deleteItemFromCart = "${url}api/carts/deleteItemFromCart";
final registerOrder = "${url}api/orders/registerOrder";
final updateQuantities = "${url}api/products/updateProductQuantities";
final deleteUserCart = "${url}api/carts/deleteUserCart";
final getUserOrders = "${url}api/orders/getUserOrders";
final updateProductRate = "${url}api/products/updateProductRate";
final getLands = "${url}api/lands/getLands";
final getUser = "${url}api/users/getUser";
final updatePostNumber = "${url}api/users/updatePostsCount";
final registerWorkRequest = "${url}api/workRequests/registerWorkRequest";
final registerProductionLine =
    "${url}api/productionLines/registerproductionLine";
final getProductutionLines = "${url}api/productionLines/getProductionLines";
final getOwnerProducts = "${url}api/products/getOwnerProducts";
final getOwnerLands = "${url}api/lands/getOwnerLands";
final getOwnerLines = "${url}api/productionLines/getOwnerLines";
final updateLand = "${url}api/lands/updateLand";
final deleteLand = "${url}api/lands/deleteLand";
final updateProduct = "${url}api/products/updateProduct";
final deleteProduct = "${url}api/products/deleteProduct";
final updateProductionLine = "${url}api/productionLines/updateProductionLine";
final deleteLine = "${url}api/productionLines/deleteLine";
final getOwnerRequests = "${url}api/workRequests/getOwnerRequests";
final takeDecision = "${url}api/workRequests/requestDecision";
final updateWorkers = "${url}api/lands/updateWorkersNum";
final getWorkerRequests = "${url}api/workRequests/getWorkerRequests";
final getLand = "${url}api/lands/getLand";
final newBooking = "${url}api/bookings/addNewBooking";
final getPrevBooked = "${url}api/bookings/getBookedTimes";
final getCustomerBookings = "${url}api/bookings/getCustomerBooking";
final getOwnerBookings = "${url}api/bookings/getOwnerBooking";
