const router = require("express").Router();
const orderController = require('../controller/orderController');
router.post('/registerOrder', orderController.registerOrder);
router.get('/getUserOrders/:username', orderController.getUserOrders);
router.post('/getDeliveryGroups', orderController.groupItems);
router.post('/getFastDeliveries', orderController.getAllOrdersWithPaths);
router.post('/getNormalDeliveries', orderController.getNormalDeliveryGroups);
router.get('/getOwnerOrders/:ownerusername', orderController.getItemsByOwnerAndPreparation);
router.put('/updateItemPreparation/:itemId', orderController.updateItemPreparation);
router.post('/updateNormalOrderStatus', orderController.updateItemStatus);
router.post('/updateFastOrderStatus', orderController.updateFastStatus);
router.get('/getAcceptedOrders/:deliveryUsername', orderController.getAcceptedOrders);
router.post('/getAcceptedFastDeliveries', orderController.getAllOrdersWithPathsForDeliveryMan);
router.post('/getAcceptedNormalDeliveries', orderController.getNormalDeliveryGroupsForDeliveryMan);
router.post('/updateNormalRecievedStatus', orderController.updateItemRecievedStatus);
router.post('/updateFastRecievedStatus', orderController.updateFastRecievedStatus);
module.exports = router;